<a href="https://colab.research.google.com/github/ydv-prince/Machine-Learning/blob/main/Lasso%2C_Ridge_and_Elastic_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('mpg')

In [3]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [4]:
df.drop("name", axis=1, inplace = True)

In [5]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [6]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [7]:
df['horsepower'].median()

93.5

In [8]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [10]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
dtype: object

In [11]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [12]:
#convert string column to numerical

df['origin'] = df['origin'].map({"usa": 1, "japan":2, "europe":3})

In [13]:
df['origin'] = df['origin'].astype(int)

In [14]:
#separate X and y
X = df.drop('mpg', axis=1)
y = df['mpg']

In [15]:
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [16]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=1)

In [19]:
X_train.shape

(278, 7)

In [20]:
X_test.shape

(120, 7)

In [21]:
#multiple linear regression model
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()

In [22]:
regression_model

LinearRegression()

In [23]:
regression_model.fit(X_train, y_train)

LinearRegression()

In [24]:
for i, col_name in enumerate(X_train.columns):
    print(f"The coefficients for {col_name} is {regression_model.coef_[i]}")

The coefficients for cylinders is -0.31761423027992997
The coefficients for displacement is 0.02623748259907894
The coefficients for horsepower is -0.018270764913124644
The coefficients for weight is -0.007487750398361904
The coefficients for acceleration is 0.050406734619713886
The coefficients for model_year is 0.8470951427061371
The coefficients for origin is 1.5190958387975042